### ISSUE TITLE
Add Home Screen Widget

### ISSUE THREAD

**Issue by brittanyarima** [brittanyarima/Steps#1]
Small, Medium, and Large Widgets. 

**Small:** showing just step count or progress bar for the day.
**Medium, Large**: showing current step count and graph.

**Comment by DandyLyons** [comment]
I would like to work on this issue please. :D

**Comment by brittanyarima** [comment]
Great!

**Comment by DandyLyons** [comment]
Sorry, beginner question: 

Could I have some guidance on what is the preferred way to set up signing, capabilities and provisioning for this project. 

- Should I change the team to be my own? 
- Should I create my own bundle identifier? 
  - If so, I assume I should create my own App group as well?

**Comment by brittanyarima** [comment]
Don't be sorry at all! I actually forgot to put together some instructions for that, so I'm glad you asked! (It's my first time maintaining a project) 

I'll put some instructions together this afternoon!

**Comment by DandyLyons** [comment]
I'm also following Mikaela Caron's project. She has some instructions that might help as a starting point. 

https://www.youtube.com/watch?v=60ivxAOUrYU&t=1500s
https://github.com/mikaelacaron/Basic-Car-Maintenance#:~:text=In%20the%20Basic%2DCar%2DMaintenance.xcconfig%20file%2C%20fill%20in%20your%20DEVELOPMENT_TEAM.

I tried to see if I could use a similar approach for this project but got stuck. Thanks for the help. Looking forward to the instructions.

**Comment by brittanyarima** [comment]
This is so helpful! Thanks for sending it over. I'm gonna setup a xcconfig
file tomorrow. But I talked with Mikaela and it sounds like for now if
you're wanting to get started, it's fine if you manually type in my bundle
id com.BrittanyRima.Steps & use you as a team. Then when you commit the
pull request I'll fix it on my end.

Hopefully I'll have this xcconfig file set up by tomorrow though if you end
up wanting to wait!
Either works.

**Comment by brittanyarima** [comment]
Ok, I added that file! You should be good to go!

**Comment by DandyLyons** [comment]
Question: Has HealthKit been implemented yet on Steps? 

I've implemented the S, M, and L widgets. I believe I'm successfully fetching the step count from UserDefaults, now. However, I'm not yet fetching the HealthKit records because on my device the App hasn't actually asked for permission to use my HealthKit. 

Perhaps there's an entitlement that I need to set up on my end? 


I did start a HealthKit fetch implementation based off of the HealthKit fetch in your StepsViewModel, but I didn't want to work on fetching from HealthKit, if we haven't finished implementing HealthKit yet. 

Here's what I have so far: 
https://github.com/DandyLyons/BrittanyArima-Steps/tree/1-add-home-screen-widget 

![Screenshot 2023-10-04 at 12 00 05 PM](https://github.com/brittanyarima/Steps/assets/72824209/0e909740-197a-4e24-81a2-2819e09c29bd)
![Screenshot 2023-10-04 at 12 02 29 PM](https://github.com/brittanyarima/Steps/assets/72824209/340348c9-c4b4-4dc5-b467-d7e5bab4355e)
![Screenshot 2023-10-04 at 12 02 58 PM](https://github.com/brittanyarima/Steps/assets/72824209/176f05c9-db1d-4524-a568-4f51adfe85fa)

**Comment by brittanyarima** [comment]
First of all, those widgets look SO GOOD!
Yes, I have a couple HealthKit calls in StepsViewModel (if you want to take
a look). That's odd that it's not asking permission on your end. This might
be something I can test and debug after we merge.

Again, this looks so good! Thanks for contributing!

**Comment by brittanyarima** [comment]
I'm seeing it's not asking for permission on my end too. I can look into
this!

**Comment by DandyLyons** [comment]
Thanks. You're too kind. Here's a pull request: https://github.com/brittanyarima/Steps/pull/43
